# Generated by Django 4.0.6 on 2022-07-24 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
