# Generated by Django 4.0.6 on 2022-07-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_message"),
        ("projects", "0008_review_owner_alter_project_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="users.profile",
            ),
        ),
    ]
