services:
  app:
    container_name: app
    build: .
    ports:
      - 8000:8000
    working_dir: /code
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data:cached

  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  postgres_data: